### PR TITLE
task/fix_component_links_according_to_iotp_v4.1

### PR DESCRIPTION
**Pull request by frbattid**
```
$ grep -r "master" docs/
docs//externals/fiware-orion/doc/manuals/admin/cli.md:    script](https://github.com/telefonicaid/fiware-orion/blob/master/scripts/httpsPrepare.sh)
docs//externals/fiware-orion/doc/manuals/admin/cli.md:    script](https://github.com/telefonicaid/fiware-orion/blob/master/scripts/httpsPrepare.sh)
docs//externals/fiware-orion/doc/manuals/admin/resources.md:    flows (e.g. the synchronization between master and slaves in a
docs//externals/fiware-orion/doc/manuals/quick_start_guide.md:    # wget --no-check-certificate https://raw.githubusercontent.com/fgalan/oauth2-example-orion-client/master/token_script.sh
docs//externals/fiware-orion/doc/manuals/user/walkthrough_apiv1.md:GitHub](https://github.com/telefonicaid/fiware-orion/blob/master/scripts/accumulator-server.py).
docs//topics/data_calculation.md:the [specification](https://github.com/telefonicaid/iotagent-node-lib/blob/master/doc/expressionLanguage.md).
docs//topics/geolocalized_entities.md:    at Carto. See [Cygnus documentation](http://fiware-cygnus.readthedocs.io/en/master/cygnus-ngsi/flume_extensions_catalogue/ngsi_cartodb_sink/index.html#section2.3.6) for more detail.
```

```
$ grep -r "develop" docs/
docs//cep.md:CEP APIs allows developers to manage rules exposing CRUD operations, and feed it with NGSI10 notifications to trigger those rules.
docs//device_api.md:Finally, after connecting your IoT devices this way you (or any other developer with the right access permissions) should be able to use the Data API to read the NGSI entity assigned to your device or see the data on the Management Portal.
docs//device_gateway.md:device specific platform and the platform standard model (NGSI). For that, different IoT Agents development frameworks
docs//externals/fiware-orion/doc/manuals/admin/cli.md:    [here](https://github.com/telefonicaid/fiware-orion/blob/develop/src/lib/logMsg/traceLevels.h)
docs//externals/fiware-orion/doc/manuals/admin/database_admin.md:location](https://github.com/telefonicaid/fiware-orion/tree/develop/test/LoadTest)
docs//externals/fiware-orion/doc/manuals/admin/logs.md:    log message. This information is useful for developers only.
docs//externals/fiware-orion/doc/manuals/admin/logs.md:    (this information is useful mainly for Orion developers).
docs//externals/fiware-orion/doc/manuals/admin/logs.md:    This type of errors should be reported to the Orion development team
docs//externals/fiware-orion/doc/manuals/admin/logs.md:    development team using the appropriate channel (StackOverflow with
docs//externals/fiware-orion/doc/manuals/admin/logs.md:| 3          | CRITICAL   | The following ERROR text appears in the 'msg' field: "Runtime Error (...)"                    | N/A                                                                                                                                                                                                                                                      | Runtime Error. The text within parenthesis in the 'msg' field containts the detailed information.            | Restart Orion Context Broker. If it persits (e.g. new Runtime Errors appear within the next hour), scale up the problem to development team.
docs//externals/fiware-orion/doc/manuals/admin/resources.md:Broker, tests done in our development and testing environment show that
docs//externals/fiware-orion/doc/manuals/code_contributions.md:external developers) that can be used as examples for programming with
docs//externals/fiware-orion/doc/manuals/code_contributions.md:<https://github.com/KurentoLegacy/kmf-orion-connector/tree/develop>
docs//externals/fiware-orion/doc/manuals/user/context_providers.md:The Context Providers and request forwarding functionality was developed
docs//externals/fiware-orion/doc/manuals/user/walkthrough_apiv1.md:be sent in this case or not. On one hand, some developers have told us
docs//externals/fiware-orion/doc/manuals/user/walkthrough_apiv1.md:one hand, some developers have told us that it might be useful to know
docs//externals/fiware-orion/doc/manuals/vagrant.md:If you want yo have an Orion Context Broker ready to develop in your machine easily we provide a Vagrant file so that you can get up and running. Just run:
docs//externals/fiware-orion/doc/manuals/vagrant.md:You just need to install Vagrant if you want to use this, and at least Virtualbox. Especially useful for those that use virtual machines to develop on a Mac or a Linux distribution that is not CentOS. Keep in mind that the Vagrant file specifies CentOS 6.5 as a base operating system.
docs//index.md:- Device-independent APIs for quick app development & lock-in prevention
docs//security.md:You, as a developer, may wonder what a subject is, and why policies are grouped around them. To simplify, a subject is
docs//security.md:[Keystone](http://developer.openstack.org/api-ref-identity-v3.html)
docs//topics/cep_new_actions.md:This set is enhanced from time to time adding new actions, according to IoT platform development roadmap.
docs//topics/cep_new_actions.md:* Request the development of the new action as part of the CEP actions set. In this case, please [fill 
docs//topics/user_permissions.md:Since [Identity Management](../authentication_api.md) of IoT Platform is based on [OpenStack Keystone](http://docs.openstack.org/developer/keystone) the following table represents relations between involved concepts:
docs//topics/which_historical_backend.md:No visualization tools are given with STH Comet. Nevertheless, its REST API could be integrated by a skilled developer with some tools such as [Grafana](http://grafana.org/).
```

### CODE REVIEW

**Comment by fgalan** [comment]
LGTM

There is a little issue about iotagente-manager-lib version adjustemnet, but I understand that @frbattid and @dmoranj will discuss about it before merging.

**Comment by fgalan** [comment]
A hint regarding grep: they would work better adding `| grep http` in order to remove some false positives.

**Comment by fgalan** [comment]
I understand this one (referes to Cygnus doc) should be fixed:

```
docs//topics/geolocalized_entities.md:    at Carto. See [Cygnus documentation](http://fiware-cygnus.readthedocs.io/en/master/cygnus-ngsi/flume_extensions_catalogue/ngsi_cartodb_sink/index.html#section2.3.6) for more detail.
```

**Comment by fgalan** [comment]
Regarding iotnode-agent-lib:

```
docs//topics/data_calculation.md:the [specification](https://github.com/telefonicaid/iotagent-node-lib/blob/master/doc/expressionLanguage.md)
```

Taking into account that the v4.1 releases for iotagent-ul and iotagent-json are 1.4.0 and 1.5.0 respectively, we can follow the dependency the corresponding package.json files:

https://github.com/telefonicaid/iotagent-ul/blob/release/1.4.0/package.json#L29
https://github.com/telefonicaid/iotagent-json/blob/release/1.5.0/package.json#L54

In both case we have:

```
 "iotagent-node-lib": "2.4.x",
```

So I undertand that release/2.4.0 should be used for the library reference.

**Comment by frbattid** [comment]
About this one:

    docs//topics/geolocalized_entities.md:    at Carto. See [Cygnus documentation](http://fiware-cygnus.readthedocs.io/en/master/cygnus-ngsi/flume_extensions_catalogue/ngsi_cartodb_sink/index.html#section2.3.6) for more detail.

It is within a commented paragraph.

**Comment by frbattid** [comment]
Please, check my last commit fixing @fgalan comments:

https://github.com/telefonicaid/fiware-iot-stack/pull/57/commits/872fa9456a81e6ea923a35119e0af5c6b2732e7d

**Comment by manucarrace** [comment]
LGTM

**Pull request merged**
